### ISSUE TITLE
Windows OS npm install Errors

### ISSUE THREAD

**Issue by Raj123456788** [Webini/node-gstreamer-launch#4]
npm ERR! code ENOSELF
npm ERR! Refusing to install package with name "node-gstreamer-launch" under a package
npm ERR! also called "node-gstreamer-launch". Did you name your project the same
npm ERR! as the dependency you're installing?
npm ERR!
npm ERR! For more information, see:
npm ERR!     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>

**Comment by Webini** [comment]
Hi, as you can see in the previous error message :

`Did you name your project the same as the dependency you're installing?`
