### ISSUE TITLE
How to get stream object?

### ISSUE THREAD

**Issue by HimanshuVerma18111989** [Webini/node-gstreamer-launch#5]
Hi,

I want to get stream object like in the below code:

Stream = require('node-rtsp-stream');
            stream = new Stream({
                    streamUrl: 'rtsp://freja.hiof.no:1935/rtplive/_definst_/hessdalen02.stream',
                    wsPort: 9999
            })
            console.log('[MASTER] created rtsp stream'+JSON.stringify(stream));
            master.localStream = stream;

Is there a way to get stream object using gstreamer-superficial?

**Comment by Webini** [comment]
Hi, you can't get the gstreamer binary stream, this package only help you to run gst-launch instance with given parameters. You can only retrieve stream of gst-launch stdout, stderr
